//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnteeoExchanger.AnteeoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthData", Namespace="http://schemas.datacontract.org/2004/07/ANTEEO_WCF")]
    [System.SerializableAttribute()]
    public partial class AuthData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string masterFidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int usrIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnString {
            get {
                return this.ConnStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnStringField, value) != true)) {
                    this.ConnStringField = value;
                    this.RaisePropertyChanged("ConnString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginError {
            get {
                return this.loginErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.loginErrorField, value) != true)) {
                    this.loginErrorField = value;
                    this.RaisePropertyChanged("loginError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string masterFid {
            get {
                return this.masterFidField;
            }
            set {
                if ((object.ReferenceEquals(this.masterFidField, value) != true)) {
                    this.masterFidField = value;
                    this.RaisePropertyChanged("masterFid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pass {
            get {
                return this.passField;
            }
            set {
                if ((object.ReferenceEquals(this.passField, value) != true)) {
                    this.passField = value;
                    this.RaisePropertyChanged("pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int usrId {
            get {
                return this.usrIdField;
            }
            set {
                if ((this.usrIdField.Equals(value) != true)) {
                    this.usrIdField = value;
                    this.RaisePropertyChanged("usrId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnteeoService.IAnteeoServicesXml_WMS")]
    public interface IAnteeoServicesXml_WMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlSysInfo", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlSysInfoResponse")]
        byte[] getXmlSysInfo(AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlSysInfo", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlSysInfoResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlSysInfoAsync(AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/generateXmlAdvice", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/generateXmlAdviceResponse")]
        byte[] generateXmlAdvice(byte[] xmlGenAdvice, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/generateXmlAdvice", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/generateXmlAdviceResponse")]
        System.Threading.Tasks.Task<byte[]> generateXmlAdviceAsync(byte[] xmlGenAdvice, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdvice", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdviceResponse")]
        byte[] modifyXmlAdvice(byte[] xmlModifyAdvice, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdvice", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdviceResponse")]
        System.Threading.Tasks.Task<byte[]> modifyXmlAdviceAsync(byte[] xmlModifyAdvice, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlAdvicePositions", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlAdvicePositionsResponse")]
        byte[] addXmlAdvicePositions(byte[] xmlAddAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlAdvicePositions", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlAdvicePositionsResponse")]
        System.Threading.Tasks.Task<byte[]> addXmlAdvicePositionsAsync(byte[] xmlAddAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdvicePositions", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdvicePositionsResponse")]
        byte[] modifyXmlAdvicePositions(byte[] xmlModifyAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdvicePositions", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlAdvicePositionsResponse")]
        System.Threading.Tasks.Task<byte[]> modifyXmlAdvicePositionsAsync(byte[] xmlModifyAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlAdviceStatus", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlAdviceStatusResponse")]
        byte[] setXmlAdviceStatus(byte[] xmlSetAdviceStatus, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlAdviceStatus", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlAdviceStatusResponse")]
        System.Threading.Tasks.Task<byte[]> setXmlAdviceStatusAsync(byte[] xmlSetAdviceStatus, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlStock", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlStockResponse")]
        byte[] getXmlStock(byte[] xmlGetStock, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlStock", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlStockResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlStockAsync(byte[] xmlGetStock, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlProduct", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlProductResponse")]
        byte[] addXmlProduct(byte[] xmlAddProd, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlProduct", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlProductResponse")]
        System.Threading.Tasks.Task<byte[]> addXmlProductAsync(byte[] xmlAddProd, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlProduct", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlProductResponse")]
        byte[] modifyXmlProduct(byte[] xmlModifyProd, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlProduct", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/modifyXmlProductResponse")]
        System.Threading.Tasks.Task<byte[]> modifyXmlProductAsync(byte[] xmlModifyProd, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/removeXmlProduct", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/removeXmlProductResponse")]
        byte[] removeXmlProduct(byte[] xmlRemoveProd, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/removeXmlProduct", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/removeXmlProductResponse")]
        System.Threading.Tasks.Task<byte[]> removeXmlProductAsync(byte[] xmlRemoveProd, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlProductsList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlProductsListResponse")]
        byte[] getXmlProductsList(byte[] xmlGetProdList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlProductsList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlProductsListResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlProductsListAsync(byte[] xmlGetProdList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlExpiredProductsList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlExpiredProductsListResponse")]
        byte[] getXmlExpiredProductsList(byte[] xmlGetExpiredProdList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlExpiredProductsList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlExpiredProductsListResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlExpiredProductsListAsync(byte[] xmlGetExpiredProdList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsStatus", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsStatusResponse")]
        byte[] getXmlOperationsStatus(byte[] xmlGetOperStatus, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsStatus", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsStatusResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlOperationsStatusAsync(byte[] xmlGetOperStatus, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsData", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsDataResponse")]
        byte[] getXmlOperationsData(byte[] xmlGetOperData, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsData", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlOperationsDataResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlOperationsDataAsync(byte[] xmlGetOperData, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlOperationsCollected", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlOperationsCollectedResponse")]
        byte[] setXmlOperationsCollected(byte[] xmlSetOperCollected, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlOperationsCollected", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/setXmlOperationsCollectedResponse")]
        System.Threading.Tasks.Task<byte[]> setXmlOperationsCollectedAsync(byte[] xmlSetOperCollected, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlBillingsList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlBillingsListResponse")]
        byte[] getXmlBillingsList(byte[] xmlGetBillingsList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlBillingsList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlBillingsListResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlBillingsListAsync(byte[] xmlGetBillingsList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlOperationsFile", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlOperationsFileResponse")]
        byte[] addXmlOperationsFile(byte[] xmlAddOperFilePart, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlOperationsFile", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/addXmlOperationsFileResponse")]
        System.Threading.Tasks.Task<byte[]> addXmlOperationsFileAsync(byte[] xmlAddOperFilePart, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlDictionariesList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlDictionariesListResponse")]
        byte[] getXmlDictionariesList(byte[] xmlGetDictionariesList, AnteeoExchanger.AnteeoService.AuthData authData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlDictionariesList", ReplyAction="http://tempuri.org/IAnteeoServicesXml_WMS/getXmlDictionariesListResponse")]
        System.Threading.Tasks.Task<byte[]> getXmlDictionariesListAsync(byte[] xmlGetDictionariesList, AnteeoExchanger.AnteeoService.AuthData authData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnteeoServicesXml_WMSChannel : AnteeoExchanger.AnteeoService.IAnteeoServicesXml_WMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnteeoServicesXml_WMSClient : System.ServiceModel.ClientBase<AnteeoExchanger.AnteeoService.IAnteeoServicesXml_WMS>, AnteeoExchanger.AnteeoService.IAnteeoServicesXml_WMS {
        
        public AnteeoServicesXml_WMSClient() {
        }
        
        public AnteeoServicesXml_WMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnteeoServicesXml_WMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnteeoServicesXml_WMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnteeoServicesXml_WMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] getXmlSysInfo(AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlSysInfo(authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlSysInfoAsync(AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlSysInfoAsync(authData);
        }
        
        public byte[] generateXmlAdvice(byte[] xmlGenAdvice, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.generateXmlAdvice(xmlGenAdvice, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> generateXmlAdviceAsync(byte[] xmlGenAdvice, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.generateXmlAdviceAsync(xmlGenAdvice, authData);
        }
        
        public byte[] modifyXmlAdvice(byte[] xmlModifyAdvice, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.modifyXmlAdvice(xmlModifyAdvice, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> modifyXmlAdviceAsync(byte[] xmlModifyAdvice, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.modifyXmlAdviceAsync(xmlModifyAdvice, authData);
        }
        
        public byte[] addXmlAdvicePositions(byte[] xmlAddAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.addXmlAdvicePositions(xmlAddAdvicePositions, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> addXmlAdvicePositionsAsync(byte[] xmlAddAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.addXmlAdvicePositionsAsync(xmlAddAdvicePositions, authData);
        }
        
        public byte[] modifyXmlAdvicePositions(byte[] xmlModifyAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.modifyXmlAdvicePositions(xmlModifyAdvicePositions, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> modifyXmlAdvicePositionsAsync(byte[] xmlModifyAdvicePositions, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.modifyXmlAdvicePositionsAsync(xmlModifyAdvicePositions, authData);
        }
        
        public byte[] setXmlAdviceStatus(byte[] xmlSetAdviceStatus, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.setXmlAdviceStatus(xmlSetAdviceStatus, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> setXmlAdviceStatusAsync(byte[] xmlSetAdviceStatus, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.setXmlAdviceStatusAsync(xmlSetAdviceStatus, authData);
        }
        
        public byte[] getXmlStock(byte[] xmlGetStock, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlStock(xmlGetStock, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlStockAsync(byte[] xmlGetStock, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlStockAsync(xmlGetStock, authData);
        }
        
        public byte[] addXmlProduct(byte[] xmlAddProd, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.addXmlProduct(xmlAddProd, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> addXmlProductAsync(byte[] xmlAddProd, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.addXmlProductAsync(xmlAddProd, authData);
        }
        
        public byte[] modifyXmlProduct(byte[] xmlModifyProd, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.modifyXmlProduct(xmlModifyProd, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> modifyXmlProductAsync(byte[] xmlModifyProd, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.modifyXmlProductAsync(xmlModifyProd, authData);
        }
        
        public byte[] removeXmlProduct(byte[] xmlRemoveProd, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.removeXmlProduct(xmlRemoveProd, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> removeXmlProductAsync(byte[] xmlRemoveProd, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.removeXmlProductAsync(xmlRemoveProd, authData);
        }
        
        public byte[] getXmlProductsList(byte[] xmlGetProdList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlProductsList(xmlGetProdList, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlProductsListAsync(byte[] xmlGetProdList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlProductsListAsync(xmlGetProdList, authData);
        }
        
        public byte[] getXmlExpiredProductsList(byte[] xmlGetExpiredProdList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlExpiredProductsList(xmlGetExpiredProdList, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlExpiredProductsListAsync(byte[] xmlGetExpiredProdList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlExpiredProductsListAsync(xmlGetExpiredProdList, authData);
        }
        
        public byte[] getXmlOperationsStatus(byte[] xmlGetOperStatus, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlOperationsStatus(xmlGetOperStatus, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlOperationsStatusAsync(byte[] xmlGetOperStatus, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlOperationsStatusAsync(xmlGetOperStatus, authData);
        }
        
        public byte[] getXmlOperationsData(byte[] xmlGetOperData, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlOperationsData(xmlGetOperData, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlOperationsDataAsync(byte[] xmlGetOperData, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlOperationsDataAsync(xmlGetOperData, authData);
        }
        
        public byte[] setXmlOperationsCollected(byte[] xmlSetOperCollected, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.setXmlOperationsCollected(xmlSetOperCollected, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> setXmlOperationsCollectedAsync(byte[] xmlSetOperCollected, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.setXmlOperationsCollectedAsync(xmlSetOperCollected, authData);
        }
        
        public byte[] getXmlBillingsList(byte[] xmlGetBillingsList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlBillingsList(xmlGetBillingsList, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlBillingsListAsync(byte[] xmlGetBillingsList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlBillingsListAsync(xmlGetBillingsList, authData);
        }
        
        public byte[] addXmlOperationsFile(byte[] xmlAddOperFilePart, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.addXmlOperationsFile(xmlAddOperFilePart, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> addXmlOperationsFileAsync(byte[] xmlAddOperFilePart, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.addXmlOperationsFileAsync(xmlAddOperFilePart, authData);
        }
        
        public byte[] getXmlDictionariesList(byte[] xmlGetDictionariesList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlDictionariesList(xmlGetDictionariesList, authData);
        }
        
        public System.Threading.Tasks.Task<byte[]> getXmlDictionariesListAsync(byte[] xmlGetDictionariesList, AnteeoExchanger.AnteeoService.AuthData authData) {
            return base.Channel.getXmlDictionariesListAsync(xmlGetDictionariesList, authData);
        }
    }
}
